name: CI Pipeline

on:
  push:
    branches:
      - 'feat/**'
      - 'bugfix/**'
      - 'test/**'
  workflow_dispatch:

jobs:
  tests:
    name: Tests runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run application tests
        run: ./gradlew test
